### ISSUE TITLE
Create a separated module for basic operations

### ISSUE THREAD

**Issue by rotilho** [thehen101/Rain#8]
Hello!

I'm working in an implementation of the Nano Node for JVM in Kotlin and there are some code that I can use from here. To avoid copy + past I'm wondering if we can move this code to a common package with byteArray encoding/decoding, address generation, address to public key, public key to address and all those common operations that everyone can use and release it in maven central.

I can do that if you allow me.

**Comment by rotilho** [comment]
I created in the meantime the repo https://github.com/rotilho/jnano-commons

Let me know if I can release it but before I'm planning some refactoring before

**Comment by thehen101** [comment]
I see what you mean - a project that contains code to interface with the Nano wallet in Java (but no implementation). This sounds like a good idea, I don't mind if you do this - the code in this repository is free to use in whatever way you would like. Just note that in some places it could probably be made more efficient.

**Comment by rotilho** [comment]
I was actually think about real implementation :) I can't see concurrent implementations using the same interfaces in case of Nano, I'm thinking more about a commons operations that range from back-end to android apps could easily use.

Thanks for let me using it :)
